### PR TITLE
v0.3

### LINKED ISSUE #1: Nitpick: Use Releases and curl instead of git clone
https://github.com/z0ph/aws-security-toolbox/blob/30fa2473065bac6c546391e39ee55b02c00cb9e8/Dockerfile#L36

Just adding this hear as a suggestion mostly AFAICT there is no reason you need git installed here other than the fact that you're cloning entire repos to install them.

However Github has a "release" feature and all the repos you're downloading utilize them. This would allow you to save installing git, just do this with curl and have a lot less work to do installing and building this image.

I also think it would make it cleaner especially because Github makes it easy to package releases for specific OS's so you could only download a .deb file if they are to make one available at some point.

Overall kudos on putting something together and trying to be useful to the community.

### LINKED ISSUE #6: Reduce Docker Image Size
Current Docker Image size: 

`aws-security-toolbox                                         latest                 79e46d6e5909                1.54GB`

- Clean cache
- Use Alpine Linux instead of Debian
- Use Packages

### PR DESCRIPTION
**Pull request by z0ph**
- Using curl and release instead of git clone
- Reduce Docker Image Size

### CODE REVIEW

**Comment by w0rldart** [comment]
This looks great! What's holding it back from being merged?

**Comment by z0ph** [comment]
> This looks great! What's holding it back from being merged?

Hey @w0rldart, this PR is not yet ready, as you can see, there is still a lot of code comments and still testing to be done on my side. Unfortunately, I've no time to work on this these days. Do you need any specific fix or enhancement?

**Comment by w0rldart** [comment]
That makes sense @z0ph thanks for letting me know. I'll keep an eye waiting for this to get merged.

Kind regards

**Comment by w0rldart** [comment]
That makes sense @z0ph thanks for letting me know. I'll keep an eye waiting for this to get merged.

Kind regards

**Pull request closed without merging**
